/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package massimialunnimarcoemailsender_client;

/**
 *
 * @author massimialunni.marco
 */
public class FrameSMTP extends javax.swing.JFrame {

    /**
     * Creates new form FrameSMTP
     */
    public FrameSMTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDest = new javax.swing.JLabel();
        lblServer = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();
        lblMittente = new javax.swing.JLabel();
        lblOggetto = new javax.swing.JLabel();
        lblTesto = new javax.swing.JLabel();
        txtServer = new javax.swing.JTextField();
        txtMittente = new javax.swing.JTextField();
        txtDest = new javax.swing.JTextField();
        txtOggetto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxLog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        atxTesto = new javax.swing.JTextArea();
        btnInvia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblDest.setText("A:");
        getContentPane().add(lblDest);
        lblDest.setBounds(310, 50, 80, 16);

        lblServer.setText("SERVER SMTP:");
        getContentPane().add(lblServer);
        lblServer.setBounds(20, 20, 120, 16);

        lblLog.setText("LOG:");
        getContentPane().add(lblLog);
        lblLog.setBounds(20, 270, 80, 16);

        lblMittente.setText("DA:");
        getContentPane().add(lblMittente);
        lblMittente.setBounds(20, 50, 80, 16);

        lblOggetto.setText("OGGETTO:");
        getContentPane().add(lblOggetto);
        lblOggetto.setBounds(20, 90, 80, 16);

        lblTesto.setText("TESTO:");
        getContentPane().add(lblTesto);
        lblTesto.setBounds(20, 120, 80, 16);
        getContentPane().add(txtServer);
        txtServer.setBounds(110, 20, 410, 22);
        getContentPane().add(txtMittente);
        txtMittente.setBounds(110, 50, 180, 22);
        getContentPane().add(txtDest);
        txtDest.setBounds(340, 50, 180, 22);
        getContentPane().add(txtOggetto);
        txtOggetto.setBounds(110, 90, 410, 22);

        atxLog.setColumns(20);
        atxLog.setRows(5);
        jScrollPane1.setViewportView(atxLog);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 500, 80);

        atxTesto.setColumns(20);
        atxTesto.setRows(5);
        jScrollPane2.setViewportView(atxTesto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 140, 500, 120);

        btnInvia.setText("INVIA EMAIL");
        btnInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviaActionPerformed(evt);
            }
        });
        getContentPane().add(btnInvia);
        btnInvia.setBounds(20, 380, 500, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviaActionPerformed
        try {
            String server = txtServer.getText();

            SMTPClient client = new SMTPClient(server, atxLog);

            String serverName = "localHost";
            client.helo(serverName);

            String from = txtMittente.getText();
            client.from(from);

            String to = txtDest.getText();
            client.to(to);

            String subject = txtOggetto.getText();

            String line;
            String message = atxTesto.getText();

            client.data(subject, message);
            client.quit();

            atxLog.append("\nMessaggio inviato correttamente!");

        } catch (Exception e) {
            System.out.println("Errore durante l'invio del messaggio: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInviaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxLog;
    private javax.swing.JTextArea atxTesto;
    private javax.swing.JButton btnInvia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblMittente;
    private javax.swing.JLabel lblOggetto;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblTesto;
    private javax.swing.JTextField txtDest;
    private javax.swing.JTextField txtMittente;
    private javax.swing.JTextField txtOggetto;
    private javax.swing.JTextField txtServer;
    // End of variables declaration//GEN-END:variables
}
